source :rubygems
gem "sinatra", ">=1.0"
gem "mongoid", "2.0.0.beta.17"
gem "bson_ext", "1.0.4"
gem 'sinatra-mongoid-config', :git => "git://github.com/flexd/sinatra-mongoid-config.git"
gem 'sinatra-cache'
gem "rspec"
gem "rack-test"
gem "haml"
gem "tilt"
gem "fastthread"
gem "activesupport"
gem "rack-flash"
gem "sinatra-redirect-with-flash"
gem "resque"
gem "rake"
gem "carrierwave"
