source :rubygems
gem 'sinatra-cookie_thief', :git => "https://github.com/kyledrake/sinatra-cookie_thief.git"
gem 'rack', :path => "~/code/rack"
gem "sinatra", ">=1.0"
gem "bson_ext", "~> 1.3"
gem "mongoid", "~> 2.0"
#gem 'sinatra-mongoid-config', :git => "git://github.com/flexd/sinatra-mongoid-config.git"
gem "rspec"
gem "rack-test"
gem "haml"
gem "rack-flash"
gem "sinatra-redirect-with-flash"
gem "resque"
gem "rake"
gem "carrierwave"
